/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supercoolbankmanager;

import java.io.IOException;
import javax.swing.ImageIcon;

/**
 *
 * @author dwayn
 */
public class BankManagerGUI extends javax.swing.JFrame {

    /**
     * Creates new form BankManagerGUI
     */
    private LoginManager2 loginManager;

    /**
     * Initializes the BankManagerGUI
     */
    public BankManagerGUI() {
        this.loginManager = new LoginManager2();
        initComponents();
        setAppIcon();
        setWelcomeName();
    }

    /**
     *
     * @param lm getting the login managers instance to pass through the logged in users username
     */
    public BankManagerGUI(LoginManager2 lm) {
        this.loginManager = lm;
        initComponents();
        setAppIcon();
        setWelcomeName();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblWelcomeName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnValidateCard = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnTransactions = new javax.swing.JButton();
        btnDaytoDay = new javax.swing.JButton();
        btnSavings = new javax.swing.JButton();
        btnPayRecipient = new javax.swing.JButton();
        btnMessages = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SCBMA");
        setMaximumSize(new java.awt.Dimension(1250, 703));
        setMinimumSize(new java.awt.Dimension(1250, 703));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblWelcomeName.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblWelcomeName.setForeground(new java.awt.Color(0, 0, 0));
        lblWelcomeName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(66, 133, 244));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Super");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(234, 67, 53));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cool");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(251, 188, 5));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Bank");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(66, 133, 244));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Manager");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(52, 168, 83));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("App");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 401, Short.MAX_VALUE)
                .addComponent(lblWelcomeName, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWelcomeName, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 90));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Developed By: Dwayne Crous");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Design Inspired By Google LLC");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 829, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 1250, 50));

        btnValidateCard.setBackground(new java.awt.Color(255, 180, 130));
        btnValidateCard.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnValidateCard.setForeground(new java.awt.Color(0, 0, 0));
        btnValidateCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supercoolbankmanager/Assets/approval.png"))); // NOI18N
        btnValidateCard.setText("Validate Card");
        btnValidateCard.setToolTipText("Feature to Validate any credit card number");
        btnValidateCard.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnValidateCard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnValidateCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidateCardActionPerformed(evt);
            }
        });
        getContentPane().add(btnValidateCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 260, 120));

        btnLogout.setBackground(new java.awt.Color(255, 154, 162));
        btnLogout.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(0, 0, 0));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supercoolbankmanager/Assets/logout(1).png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setToolTipText("Takes you back to sign in screen");
        btnLogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 580, 180, 70));

        btnTransactions.setBackground(new java.awt.Color(183, 228, 199));
        btnTransactions.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnTransactions.setForeground(new java.awt.Color(0, 0, 0));
        btnTransactions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supercoolbankmanager/Assets/transaction-history.png"))); // NOI18N
        btnTransactions.setText("Transactions");
        btnTransactions.setToolTipText("Takes you to your Transaction History");
        btnTransactions.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnTransactions.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTransactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransactionsActionPerformed(evt);
            }
        });
        getContentPane().add(btnTransactions, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 260, 120));

        btnDaytoDay.setBackground(new java.awt.Color(153, 255, 255));
        btnDaytoDay.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnDaytoDay.setForeground(new java.awt.Color(0, 0, 0));
        btnDaytoDay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supercoolbankmanager/Assets/credit-card.png"))); // NOI18N
        btnDaytoDay.setText(" Day to Day");
        btnDaytoDay.setToolTipText("Takes you to your Day to Day Account");
        btnDaytoDay.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDaytoDay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDaytoDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaytoDayActionPerformed(evt);
            }
        });
        getContentPane().add(btnDaytoDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 260, 120));

        btnSavings.setBackground(new java.awt.Color(255, 231, 155));
        btnSavings.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSavings.setForeground(new java.awt.Color(0, 0, 0));
        btnSavings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supercoolbankmanager/Assets/savings.png"))); // NOI18N
        btnSavings.setText("    Savings  ");
        btnSavings.setToolTipText("Takes you to your savings account");
        btnSavings.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSavings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSavings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavingsActionPerformed(evt);
            }
        });
        getContentPane().add(btnSavings, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 260, 120));

        btnPayRecipient.setBackground(new java.awt.Color(247, 197, 204));
        btnPayRecipient.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnPayRecipient.setForeground(new java.awt.Color(0, 0, 0));
        btnPayRecipient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supercoolbankmanager/Assets/transaction.png"))); // NOI18N
        btnPayRecipient.setText(" Pay Recipient ");
        btnPayRecipient.setToolTipText("Feature to pay a recipient");
        btnPayRecipient.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnPayRecipient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPayRecipient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayRecipientActionPerformed(evt);
            }
        });
        getContentPane().add(btnPayRecipient, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, 260, 120));

        btnMessages.setBackground(new java.awt.Color(214, 194, 242));
        btnMessages.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnMessages.setForeground(new java.awt.Color(0, 0, 0));
        btnMessages.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supercoolbankmanager/Assets/comment.png"))); // NOI18N
        btnMessages.setText("    Messages ");
        btnMessages.setToolTipText("Account and Transactional messages.");
        btnMessages.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnMessages.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMessages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMessagesActionPerformed(evt);
            }
        });
        getContentPane().add(btnMessages, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, 260, 120));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supercoolbankmanager/Assets/Gradient_Background.png"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1250, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This is a button to logout of your current account,  take you back to the login 
     * screen and display a notification saying whether you logged out successfully
     */
    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        LoginScreenGUI loginScreen = new LoginScreenGUI();
        loginScreen.setVisible(true);
        this.setVisible(false);

        try {
            String title = "You Have Logged Out";
            String message = "You have logged into the application.";
            String imagePath = "C:\\Users\\dwayn\\Desktop\\Dev\\Java\\SuperCoolBankManager\\src\\supercoolbankmanager\\Assets\\icon.png";

            String command = String.format(
                    "powershell -Command \"[Windows.UI.Notifications.ToastNotificationManager, Windows.UI.Notifications, ContentType = WindowsRuntime] | Out-Null; "
                    + "$template = [Windows.UI.Notifications.ToastTemplateType]::ToastImageAndText02; "
                    + "$xml = [Windows.UI.Notifications.ToastNotificationManager]::GetTemplateContent($template); "
                    + "$textNodes = $xml.GetElementsByTagName('text'); "
                    + "$textNodes[0].AppendChild($xml.CreateTextNode('%s')) | Out-Null; "
                    + "$textNodes[1].AppendChild($xml.CreateTextNode('%s')) | Out-Null; "
                    + "$imageNodes = $xml.GetElementsByTagName('image'); "
                    + "$imageNodes[0].SetAttribute('src', '%s'); "
                    + "$imageNodes[0].SetAttribute('alt', 'Notification Icon'); "
                    + "$toast = [Windows.UI.Notifications.ToastNotification]::new($xml); "
                    + "[Windows.UI.Notifications.ToastNotificationManager]::CreateToastNotifier('SuperCoolBankManager').Show($toast);\"",
                    title, message, imagePath
            );
            Runtime.getRuntime().exec(command);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * This is a button that directs you to the Card Validation page/feature
     */
    private void btnValidateCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidateCardActionPerformed
        // TODO add your handling code here:
        ValidateCardGUI validateCard = new ValidateCardGUI(this);
        validateCard.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnValidateCardActionPerformed

    /**
     * This is a button that directs you to the day-to-day account page/feature
     */
    private void btnDaytoDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaytoDayActionPerformed
        // TODO add your handling code here:
        DayToDayGUI dayToDay = new DayToDayGUI(loginManager, this);
        dayToDay.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDaytoDayActionPerformed

    /**
     * This is a button that directs you to the savings account page/feature
     */
    private void btnSavingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavingsActionPerformed
        // TODO add your handling code here:
        SavingsGUI savings = new SavingsGUI(loginManager, this);
        savings.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSavingsActionPerformed

    /**
     * This is a button that directs you to the pay recipient page/feature
     */
    private void btnPayRecipientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayRecipientActionPerformed
        // TODO add your handling code here:
        PayRecipientGUI payRecipient = new PayRecipientGUI(loginManager, this);
        payRecipient.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPayRecipientActionPerformed

    /**
     * This is a button that directs you to the recent and all transactions page
     */
    private void btnTransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransactionsActionPerformed
        // TODO add your handling code here:
        TransactionsGUI transactions  = new TransactionsGUI(loginManager, this);
        transactions.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTransactionsActionPerformed

    /**
     * This is a button that directs you to the recent and all messages page
     */
    private void btnMessagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMessagesActionPerformed
        // TODO add your handling code here:
        MessagesGUI messages = new MessagesGUI(loginManager, this);
        messages.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMessagesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankManagerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BankManagerGUI().setVisible(true);
            }
        });
    }

    /**
     * This is a method that runs as soon as the BankManagerGUI is created to set the app icon in the taskbar and title bar
     */
    private void setAppIcon() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/supercoolbankmanager/Assets/icon.png"));
        setIconImage(icon.getImage());
    }

    /**
     * This is a method that runs as soon as the BankManagerGUI is created to set the logged in users username in the top right corner
     */
    private void setWelcomeName() {
        lblWelcomeName.setText("Welcome back, " + loginManager.getLoggedInUser());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDaytoDay;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMessages;
    private javax.swing.JButton btnPayRecipient;
    private javax.swing.JButton btnSavings;
    private javax.swing.JButton btnTransactions;
    private javax.swing.JButton btnValidateCard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblWelcomeName;
    // End of variables declaration//GEN-END:variables
}
