package supercoolbankmanager;

import java.io.IOException;
import javax.swing.ImageIcon;

/**
 *
 * @author dwayn
 */
public class LoginScreenGUI extends javax.swing.JFrame {

    /**
     * Creates new form LoginScreenGUI
     */
    public LoginScreenGUI() {
        initComponents();
        setAppIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnCreateAccount = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txfNewUserName = new javax.swing.JTextField();
        txfNewUserPassword = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txfExistingUserName = new javax.swing.JTextField();
        psfExistingPassword = new javax.swing.JPasswordField();
        psfConfirmPassword = new javax.swing.JPasswordField();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SCBMA");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(66, 133, 244));
        jLabel2.setText("Super");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(234, 67, 53));
        jLabel3.setText("Cool");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(251, 188, 5));
        jLabel4.setText("Bank");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(66, 133, 244));
        jLabel5.setText("Manager");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(52, 168, 83));
        jLabel1.setText("App");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(754, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 90));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Existing User");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 200, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Login");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 100, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("New User");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Confirm Password:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 220, 50));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("User Name:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 140, 50));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Password:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 350, 120, 50));

        btnCreateAccount.setBackground(new java.awt.Color(52, 168, 83));
        btnCreateAccount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCreateAccount.setForeground(new java.awt.Color(0, 0, 0));
        btnCreateAccount.setText("Create Account");
        btnCreateAccount.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCreateAccount.setBorderPainted(false);
        btnCreateAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccountActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreateAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, 180, 60));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Developed By: Dwayne Crous");

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Design Inspired By Google LLC");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 828, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 1250, 50));

        txfNewUserName.setBackground(new java.awt.Color(204, 204, 204));
        txfNewUserName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txfNewUserName.setForeground(new java.awt.Color(0, 0, 0));
        txfNewUserName.setToolTipText("Enter your desired user name here.");
        txfNewUserName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        getContentPane().add(txfNewUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 210, 50));

        txfNewUserPassword.setBackground(new java.awt.Color(204, 204, 204));
        txfNewUserPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txfNewUserPassword.setForeground(new java.awt.Color(0, 0, 0));
        txfNewUserPassword.setToolTipText("Enter the password you want to create.");
        txfNewUserPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        getContentPane().add(txfNewUserPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 210, 50));

        btnLogin.setBackground(new java.awt.Color(66, 133, 244));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(0, 0, 0));
        btnLogin.setText("Login");
        btnLogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogin.setBorderPainted(false);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 530, 180, 60));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Password:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 350, -1, 50));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("User Name:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, -1, 50));

        txfExistingUserName.setBackground(new java.awt.Color(204, 204, 204));
        txfExistingUserName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txfExistingUserName.setForeground(new java.awt.Color(0, 0, 0));
        txfExistingUserName.setToolTipText("Enter your account username.");
        txfExistingUserName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        getContentPane().add(txfExistingUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 260, 210, 50));

        psfExistingPassword.setBackground(new java.awt.Color(204, 204, 204));
        psfExistingPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        psfExistingPassword.setForeground(new java.awt.Color(0, 0, 0));
        psfExistingPassword.setToolTipText("Enter your account password.");
        psfExistingPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        getContentPane().add(psfExistingPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 350, 210, 50));

        psfConfirmPassword.setBackground(new java.awt.Color(204, 204, 204));
        psfConfirmPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        psfConfirmPassword.setForeground(new java.awt.Color(0, 0, 0));
        psfConfirmPassword.setToolTipText("Enter your account password.");
        psfConfirmPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        getContentPane().add(psfConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 210, 50));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supercoolbankmanager/Assets/Gradient_Background.png"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1250, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Button to create the users new account and save it to the database
     */
    private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountActionPerformed
        // TODO add your handling code here:
        LoginManager2 lm = new LoginManager2();

        //getting the users information from the text fields
        String userName = txfNewUserName.getText();
        String password = txfNewUserPassword.getText();
        String confirmPassword = psfConfirmPassword.getText();

        //writing the users details to the database
        lm.writeUserDetailsToDB(userName, password, confirmPassword);

        //resetting the text fields after the details have been written to database
        txfNewUserName.setText("");
        txfNewUserPassword.setText("");
        psfConfirmPassword.setText("");
    }//GEN-LAST:event_btnCreateAccountActionPerformed

    /**
     * Button to fetch login details and do a check to see if login details are valid.
     */
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {
        //initiating a new LoginManager2 instance
        LoginManager2 lm = new LoginManager2();

        //getting the users username and password from text and password field
        String userName = txfExistingUserName.getText();
        String password = psfExistingPassword.getText();

        //checking if the login details are valid
        //if login details match then redirect to main menu and display login successful notification
        if (lm.loginDetailsCheck(userName, password) == true) {
            BankManagerGUI menuGUI = new BankManagerGUI(lm);
            menuGUI.setVisible(true);
            this.setVisible(false);

            try {
                String title = "Login Successful :)";
                String message = "You have logged into the application.";
                String imagePath = "C:\\Users\\dwayn\\Desktop\\SuperCoolBankManager\\src\\supercoolbankmanager\\Assets\\icon.png";

                String command = String.format(
                        "powershell -Command \"[Windows.UI.Notifications.ToastNotificationManager, Windows.UI.Notifications, ContentType = WindowsRuntime] | Out-Null; "
                        + "$template = [Windows.UI.Notifications.ToastTemplateType]::ToastImageAndText02; "
                        + "$xml = [Windows.UI.Notifications.ToastNotificationManager]::GetTemplateContent($template); "
                        + "$textNodes = $xml.GetElementsByTagName('text'); "
                        + "$textNodes[0].AppendChild($xml.CreateTextNode('%s')) | Out-Null; "
                        + "$textNodes[1].AppendChild($xml.CreateTextNode('%s')) | Out-Null; "
                        + "$imageNodes = $xml.GetElementsByTagName('image'); "
                        + "$imageNodes[0].SetAttribute('src', '%s'); "
                        + "$imageNodes[0].SetAttribute('alt', 'Notification Icon'); "
                        + "$toast = [Windows.UI.Notifications.ToastNotification]::new($xml); "
                        + "[Windows.UI.Notifications.ToastNotificationManager]::CreateToastNotifier('SuperCoolBankManager').Show($toast);\"",
                        title, message, imagePath
                );
                Runtime.getRuntime().exec(command);
            } catch (IOException e) {
                e.printStackTrace();
            }
        } else {
            //if login details dont match the send notification that login details or username dont match
            try {
                String title = "Login Failed :(  Wrong Username or Password!";
                String message = "You have failed to log into the application.";
                String imagePath = "C:\\Users\\dwayn\\Desktop\\SuperCoolBankManager\\src\\supercoolbankmanager\\Assets\\icon.png";

                String command = String.format(
                        "powershell -Command \"[Windows.UI.Notifications.ToastNotificationManager, Windows.UI.Notifications, ContentType = WindowsRuntime] | Out-Null; "
                        + "$template = [Windows.UI.Notifications.ToastTemplateType]::ToastImageAndText02; "
                        + "$xml = [Windows.UI.Notifications.ToastNotificationManager]::GetTemplateContent($template); "
                        + "$textNodes = $xml.GetElementsByTagName('text'); "
                        + "$textNodes[0].AppendChild($xml.CreateTextNode('%s')) | Out-Null; "
                        + "$textNodes[1].AppendChild($xml.CreateTextNode('%s')) | Out-Null; "
                        + "$imageNodes = $xml.GetElementsByTagName('image'); "
                        + "$imageNodes[0].SetAttribute('src', '%s'); "
                        + "$imageNodes[0].SetAttribute('alt', 'Notification Icon'); "
                        + "$toast = [Windows.UI.Notifications.ToastNotification]::new($xml); "
                        + "[Windows.UI.Notifications.ToastNotificationManager]::CreateToastNotifier('SuperCoolBankManager').Show($toast);\"",
                        title, message, imagePath
                );
                Runtime.getRuntime().exec(command);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreenGUI().setVisible(true);
            }
        });
    }

    /**
     * Sets the app icon in taskbar and title bar
     */
    private void setAppIcon() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/supercoolbankmanager/Assets/icon.png"));
        setIconImage(icon.getImage());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateAccount;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JPasswordField psfConfirmPassword;
    private javax.swing.JPasswordField psfExistingPassword;
    private javax.swing.JTextField txfExistingUserName;
    private javax.swing.JTextField txfNewUserName;
    private javax.swing.JTextField txfNewUserPassword;
    // End of variables declaration//GEN-END:variables
}
