/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supercoolbankmanager;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dwayn
 */
public class SavingsGUI extends javax.swing.JFrame {

    /**
     * Creates new form SavingsGUI
     */
    
    private LoginManager2 loginManager;
    private MainManager mm = new MainManager();
    private BankManagerGUI parentWindow;
    
    /**
     * Initializes the SavingsGUI
     */
    public SavingsGUI() {
        this.loginManager = new LoginManager2();
        initComponents();
        setAppIcon();
        loadTransactionsIntoTable();
    }
    
    /**
     *
     * @param lm getting the login managers instance to pass through the logged in users username
     * @param parentWindow setting the BankManagerGUI as the parentWindow to carry through same instance
     */
    public SavingsGUI(LoginManager2 lm, BankManagerGUI parentWindow) {
        this.loginManager = lm;
        this.parentWindow = parentWindow;
        initComponents();
        setAppIcon();
        loadTransactionsIntoTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txfAvailableBalance = new javax.swing.JTextField();
        btnWithdrawFromBalance = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnAddToBalance = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBDW = new javax.swing.JTable();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SCBMA");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(66, 133, 244));
        jLabel2.setText("Super");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(52, 168, 83));
        jLabel3.setText("App");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(234, 67, 53));
        jLabel4.setText("Cool");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(251, 188, 5));
        jLabel5.setText("Bank");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(66, 133, 244));
        jLabel6.setText("Manager");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(751, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 90));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Developed By: Dwayne Crous");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Design Inspired By Google LLC");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 832, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel8)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 1250, 50));

        jPanel3.setBackground(new java.awt.Color(66, 133, 244));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(102, 153, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Available Balance");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 210, 40));

        txfAvailableBalance.setEditable(false);
        txfAvailableBalance.setBackground(new java.awt.Color(153, 255, 255));
        txfAvailableBalance.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txfAvailableBalance.setForeground(new java.awt.Color(0, 0, 0));
        txfAvailableBalance.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfAvailableBalance.setBorder(null);
        txfAvailableBalance.setCaretColor(new java.awt.Color(51, 51, 51));
        txfAvailableBalance.setSelectionColor(new java.awt.Color(153, 255, 255));
        jPanel4.add(txfAvailableBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 190, 40));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 380, 100));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 420, 140));

        btnWithdrawFromBalance.setBackground(new java.awt.Color(255, 153, 153));
        btnWithdrawFromBalance.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnWithdrawFromBalance.setForeground(new java.awt.Color(0, 0, 0));
        btnWithdrawFromBalance.setText("Withdraw from balance");
        btnWithdrawFromBalance.setToolTipText("");
        btnWithdrawFromBalance.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnWithdrawFromBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawFromBalanceActionPerformed(evt);
            }
        });
        getContentPane().add(btnWithdrawFromBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 180, 60));

        btnBack.setBackground(new java.awt.Color(255, 154, 162));
        btnBack.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 0, 0));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supercoolbankmanager/Assets/logout(1).png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.setToolTipText("Takes you back to the main menu.");
        btnBack.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 100, 140, 60));

        btnAddToBalance.setBackground(new java.awt.Color(255, 255, 153));
        btnAddToBalance.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAddToBalance.setForeground(new java.awt.Color(0, 0, 0));
        btnAddToBalance.setText("Add to Balance");
        btnAddToBalance.setToolTipText("");
        btnAddToBalance.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAddToBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToBalanceActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddToBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 180, 60));

        tblBDW.setBackground(new java.awt.Color(255, 255, 255));
        tblBDW.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblBDW.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Available Balance", "Deposits", "Withdrawels", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBDW.setColumnSelectionAllowed(true);
        tblBDW.setFocusTraversalPolicyProvider(true);
        jScrollPane2.setViewportView(tblBDW);
        tblBDW.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (tblBDW.getColumnModel().getColumnCount() > 0) {
            tblBDW.getColumnModel().getColumn(0).setResizable(false);
            tblBDW.getColumnModel().getColumn(1).setResizable(false);
            tblBDW.getColumnModel().getColumn(2).setResizable(false);
            tblBDW.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 1100, 370));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supercoolbankmanager/Assets/Gradient_Background.png"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1250, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Button to add to the current savings balance, saves transaction to database and refreshes table
     */
    private void btnAddToBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToBalanceActionPerformed
        // TODO add your handling code here:
        double amountToDeposit = Double.parseDouble(JOptionPane.showInputDialog("How much would you like to deposit?"));
        mm.insertTransaction("SavingsTransactions", loginManager.getLoggedInUser(), amountToDeposit, 0);
        mm.insertMessage(loginManager.getLoggedInUser(), "Deposited R" + amountToDeposit + " to Savings Account");
        loadTransactionsIntoTable();
    }//GEN-LAST:event_btnAddToBalanceActionPerformed

    /**
     * Button to withdraw from the current savings balance, saves transaction to database and refreshes table
     */
    private void btnWithdrawFromBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawFromBalanceActionPerformed
        // TODO add your handling code here:
        double amountToWithdraw = Double.parseDouble(JOptionPane.showInputDialog("How much would you like to withdraw?"));
        mm.insertTransaction("SavingsTransactions", loginManager.getLoggedInUser(), 0, amountToWithdraw);
        mm.insertMessage(loginManager.getLoggedInUser(), "Withdrew R" + amountToWithdraw + " from Savings Account");
        loadTransactionsIntoTable();
    }//GEN-LAST:event_btnWithdrawFromBalanceActionPerformed

    /**
     * Button to take you back to the main menu while carrying with the same instance
     */
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        parentWindow.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SavingsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SavingsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SavingsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SavingsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SavingsGUI().setVisible(true);
            }
        });
    }
    
    /**
     * Loads the transactions into the table from the database
     */
    private void loadTransactionsIntoTable() {
        //creates the table model and sets the row count to 0
        DefaultTableModel model = (DefaultTableModel) tblBDW.getModel();
        model.setRowCount(0);
        
        //fetches the available balance, deposits, withdrawals and transaction dates from the database and stores them in arrays
        double[] availBal = mm.displaySavingsAvailableBal(loginManager.getLoggedInUser());
        double[] deposits = mm.displaySavingsDeposits(loginManager.getLoggedInUser());
        double[] withdrawels = mm.getSavingsWithdrawals(loginManager.getLoggedInUser());
        String[] dates = mm.displaySavingsDates(loginManager.getLoggedInUser());
        
        //loops through the array and populates the table with a new row for each entry
        for (int i = 0; i < deposits.length; i++) {
            model.addRow(new Object[]{availBal[i],"+ R" + deposits[i], "- R" + withdrawels[i], dates[i]});
            
            if (availBal.length > 0) {
                txfAvailableBalance.setText("R" + availBal[availBal.length - 1]);
            }
        }
    }
    
    /**
     * Sets the app icon in the taskbar and the title bar
     */
    private void setAppIcon() {
        ImageIcon icon = new ImageIcon(getClass().getResource("/supercoolbankmanager/Assets/icon.png"));
        setIconImage(icon.getImage());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToBalance;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnWithdrawFromBalance;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JTable tblBDW;
    private javax.swing.JTextField txfAvailableBalance;
    // End of variables declaration//GEN-END:variables
}
